services:
  postgres:
    ports: !override
      - "${NATIVE_POSTGRES_PORT:-15432}:5432"

  wukongim:
    environment:
      WK_WEBHOOK_HTTPADDR: http://host.docker.internal:18000/v1/integrations/wukongim/webhook
    ports: !override
      - "5001:5001"
      - "5200:5200"
