export const operationsWorkspaceZh = {
  createPlan: '新建套餐草稿', title: '域见运营后台', subtitle: '商家、授权与统一 AI 服务', overview: '运营概览', companies: '商家与授权', models: '模型中心', plans: '套餐与试用', finance: '订单与财务', monitor: '系统监控', audits: '操作记录',
  overviewHint: '查看运营状态，优先处理即将到期和待核对事项。', companiesHint: '管理商家账号、套餐授权与 AI 额度。', modelsHint: '统一配置所有商家使用的模型服务。', plansHint: '维护套餐、试用额度与激活码。', financeHint: '处理订单、退款、开票和对账。', monitorHint: '查看服务状态与任务执行情况。', auditsHint: '核对运营操作人、原因和变更结果。',
  refresh: '刷新', retry: '重试', loading: '正在加载…', empty: '暂无记录', error: '加载失败，请重试', back: '返回商家列表', detail: '查看详情', search: '搜索', searchLabel: '商家名称或登录邮箱', allStates: '所有状态', expiring: '7 天内到期', total: '共 {{count}} 家商家', previous: '上一页', next: '下一页', page: '第 {{page}} 页',
  company: '商家', plan: '套餐', state: '状态', expiry: '到期时间', seats: '人工坐席', credits: '剩余 AI 次数', exceptions: '订单待核对', actions: '操作', unnamed: '未配置', unlimited: '未设置', reserved: '含 {{count}} 个邀请预留',
  states: { enabled: '有效授权（含试用）', legacy: '待配置授权', pending: '待激活', trial: '试用中', active: '已授权', expired: '已到期', suspended: '已暂停' },
  totalCompanies: '商家总数', enabledCompanies: '有效授权', expiringCompanies: '即将到期', unresolvedOrders: '订单待核对', failedTasks: '任务待处理', pendingInvoices: '待开票', checkedAt: '更新于 {{time}}', quickActions: '常用操作', manageCompanies: '管理商家授权', configureModels: '配置统一模型', managePlans: '管理套餐与试用', overviewNote: '点击统计项进入对应管理页面。授权是否有效由状态和实际到期时间共同决定。',
  basic: '基本信息', members: '用户账号', authorization: '授权与额度', history: '变更记录', created: '创建时间', identifier: '商家 ID', override: '运营授权有效至', account: '登录邮箱 / 账号', name: '姓名', role: '角色', enabled: '已启用', disabled: '已停用', verified: '邮箱已验证', unverified: '邮箱未验证', openSessions: '接待中会话', admin: '管理员', user: '客服成员', editMember: '管理账号', resetEmail: '发送密码重置邮件',
  authorizationHint: '选择已发布套餐，并设置到期时间与坐席上限。选择套餐不会自动赠送每月额度；本次追加的 AI 次数有效至授权到期。已有订单和额度明细可在财务页面核对。', noPlans: '请先在“套餐与试用”发布一个套餐，再配置商家授权。', extraCredits: '本次追加 AI 次数', reason: '操作原因（至少 5 个字）', preview: '预览授权变更', confirm: '确认生效', cancel: '取消', before: '变更前', after: '变更后', confirmTitle: '确认授权变更', suspendedHint: '该商家已暂停，本次授权不会自动恢复服务。', saved: '修改已保存', seatsHint: '已占用 {{used}} 个坐席，另有 {{reserved}} 个邀请预留。',
  adjustCredits: '调整 AI 额度', suspend: '暂停服务', restore: '恢复服务', delta: '调整次数（正数增加，负数扣除）', creditHint: '扣除只影响尚未使用且未预占的次数；追加次数需设置有效期。', stateHint: '将变更商家的服务状态，套餐、订单和历史记录会继续保留。恢复后仍需具有有效授权。', memberHint: '账号权限变更会让旧登录凭证失效。系统会保护最后一个管理员；停用账号前需转交正在接待的会话。', emailHint: '重置邮件发送到该账号已验证的邮箱，由账号本人设置新密码。', emailQueued: '密码重置邮件已加入发送队列',
  operator: '操作人', action: '操作类型', time: '时间', changes: '查看变更明细', summary: '当前配置', services: '编辑服务与默认模型', usage: '调用记录', connectionTest: '测试服务连接', testHint: '测试已保存的服务地址和凭证；不代表所有模型的实际推理均已验证。未保存的修改不参与测试。', version: '配置版本 {{version}}', model: '默认模型', service: '模型服务', credential: '凭证', configured: '已配置', missing: '未配置', sync: '同步状态', syncComplete: '所有商家配置已同步', syncPending: '正在同步 / 待同步', syncFailed: '同步失败，请核对服务后重新发布',
  financialTabs: { orders: '订单', refunds: '退款', invoices: '发票', reconciliation: '对账', quotaReview: '额度核对' }, monitorTabs: { health: '服务状态', tasks: '任务处理', readiness: '上线检查' }, planTabs: { catalogue: '套餐管理', policy: '试用规则', codes: '试用激活码' },
  auditActions: { 'authorization.change': '商家授权调整', 'member.change': '账号权限调整', 'member.reset_email': '发送密码重置邮件', 'quota.adjust': 'AI 额度调整', 'company.suspend': '暂停商家服务', 'company.restore': '恢复商家服务', shared_models_change: '统一模型发布', task_retry: '任务重试' },
};

export const operationsWorkspaceEn = operationsWorkspaceZh;
